server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bidu
    username: root
<<<<<<< HEAD
    password: minh071205
=======
    password: Song161105@
>>>>>>> 56102eb6ed7baa79f9f9e02dd6c784921ee4b16d
  jpa:
    hibernate:
      ddl-auto: update

cloudinary:
  cloud-name: dzrhf1hwk
  api-key: 252239671882344
  api-secret: TUSE_ajDGgftHMcQPvWxXokNA7I

