server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bidu
    username: root
    password: Song161105@
  jpa:
    hibernate:
      ddl-auto: update

cloudinary:
  cloud-name: dzrhf1hwk
  api-key: 252239671882344
  api-secret: TUSE_ajDGgftHMcQPvWxXokNA7I

